services:
  db:
    image: pgvector/pgvector:pg16
    container_name: aicareer-db
    restart: always
    environment:
      - POSTGRES_USER=vor
      - POSTGRES_PASSWORD=coolpassword1234
      - POSTGRES_DB=aicareer_bridge
    volumes:
      - ./storage/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: aicareer-backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_TIMEOUT_SECONDS=${OLLAMA_TIMEOUT_SECONDS}
    ports:
      - "8000:8000"
    depends_on:
      - db
